# (PART\*) Transporte y leyes de conservación {-}

# Cantidades conservadas

## Problemas homogéneos

Sea $v:\mathbb R^n\to \mathbb R^n$ un campo vectorial suave y acotado, como tal genera un flujo $\phi:\mathbb R^n\times\mathbb R\to \mathbb R^n$ definido por medio del problema de valores iniciales
$$
\partial_t\phi(x,t) = v(\phi(x,t)), \qquad \phi(x,0)=x.
$$

Una función $u:\mathbb R^n\to \mathbb R$ se dice que es una **cantidad conservada** de $v$, si $u$ permanece constante a lo largo del flujo $\phi$. Es decir
$$
u(\phi(x,t)) = u(x) \qquad \forall \, t\in\mathbb R.
$$
Si $u$ es además diferenciable esto equivale a la ecuación parcial lineal de primer orden
$$
v \cdot Du = 0.
(\#eq:eq1)
$$

Por un lado, conocer una cantidad conservada $u$ nos ayuda a resolver las EDOs $x'=v(x)$, dado que las trayectorias permanecen en los conjuntos de nivel de $u$. Por otro lado, la EDO asociada a la EDP \@ref(eq:eq1) se conoce como la **ecuación característica** y nos ayudan a calcular la solución de la EDP dado que $u$ debe permanecer constante a lo largo de estas trayectorias.

---

:::{.example}
Dado un vector constante $v = (v_1,\ldots,v_n)\in \mathbb R$, consideremos el problema
$$
v\cdot Du = 0.
$$
Este tiene asociada la ecuación característica $x'=v$ (es decir el sistema $x_i'=v_i$) cuya solución es $x(t)=x_0+tv$. Dada que cualquier solución de la EDP debe permanecer constante a lo largo de esta trayectoria tenemos que
$$
u(x_0+tv) = u(x_0).
$$
Si $u$ estuviese predeterminada en una región $F\subseteq \mathbb R^n$ dada como la función $u_0$, entonces es conveniente tomar la posición inicial $x_0$ en dicha región. Por ejemplo, si $F = \{x_1=0\}$ y $v=(v_1,\ldots,v_n)$ no es paralelo a $F$, es decir $v_1\neq0$, entonces podemos conectar cualquier punto $x=(x_1,\ldots,x_n)\in\mathbb R^n$ con algún punto $x_0=(0,x_{0,2},\ldots,x_{0,n})\in F$ tal que $x_0+tv = x$ y por lo tanto $u(x) = u_0(x_0)$. En este caso particular podemos simplemente calcular $x_0$ y $t$ y obtener una fórmula explícita para la solución
$$
\begin{aligned}
tv_1 = x_1 \qquad&\Rightarrow\qquad t=x_1/v_1,\\
x_{0,i} + tv_i = x_i \text{ si } i\geq 2 \qquad&\Rightarrow\qquad x_{0,i} = x_i - x_1v_i/v_1,\\ 
u(x) = u_0(x_0) \qquad&\Rightarrow\qquad u(x) = u_0(0,x_2 - x_1v_2/v_1,\ldots,x_n - x_1v_n/v_1)
\end{aligned}
$$
:::

---

:::{.exercise}
Calcula $u:\mathbb R^2\to \mathbb R$ tal que
$$
\begin{cases}
y\partial_x u = x\partial_y u \text{ en } \mathbb R^2\setminus\{y=0,x\geq 0\},\\
u = u_0 \text{ en } \{y=0,x\geq 0\}.
\end{cases}
$$
:::

<details>
<summary>Solución</summary>
</details>

---

:::{.exercise}
Explica como se podría extender la teoría al problema de Cauchy donde $u:\mathbb R^n\times[0,\infty)\to \mathbb R$ depende de una variable espacial $x\in\mathbb R^n$ y una temporal $t\in[0,\infty)$ y satisface en cambio el problema de valores iniciales
$$
\begin{cases}
\partial_t u + v\cdot Du = 0 \text{ en } \mathbb R^n,\\
u = u_0 \text{ en } \{t= 0\}
\end{cases}
$$
:::

<details>
<summary>Solución</summary>
</details>

---

:::{.example}
**Ley de conservación de la energía**

Un sistema mecánico se dice **conservativo** si la fuerza es menos el gradiente un potencial $U$
$$
mv' = -DU(x), \qquad v=x'.
$$
La energía del sistema es la suma de la cinética y potencial
$$
E(x,v) = \frac{1}{2}m|v|^2 + U(x).
$$
La **ley de la conservación de la energía** dice que la energía total es constante. Comprobémoslo calculando la derivada temporal de $E$.
$$
\frac{d}{dt}E(x(t),v(t)) = x'\partial_x E + v'\partial_v E=v\cdot DU + \frac{(-DU)}{m}\cdot m v = 0.
$$
Dicho de otra forma, la energía total satisface la ecuación $(v,-DU/m)\cdot DE=0$.
:::

---

:::{.exercise}
Considera el sistema mecánico de fuerzas centrales,
$$
mx'' = f(|x|)x.
$$
Demuestra que el momento angular $L_{ij} = x_ix_j'-x_jx_i'$ es una cantidad conservada del sistema.
:::

<details>
<summary>Solución</summary>
</details>

---

:::{.example}
Consideremos el sistema de ecuaciones
$$
x' = f(x,y),\qquad
y' = g(x,y).
$$
La trayectoria del sistema consiste del lugar geométrico trazado por la solución. La ecuación se dice **exacta** si las trayectorias son el conjunto de nivel de una función $u$, equivalentemente el campo $(f,g)$ debe ser perpendicular a $(\partial_xu,\partial_y u)$. Esto sucede en particular si $(f,g) = (-\partial_y u,\partial_x u)$ lo cual implica $\operatorname{div}((f,g))= \partial_x f+\partial_y g=0$. Esta hipótesis no solamente es necesaria, si no también suficiente para encontrar $u$ tal que
$$
g(x,y) = \partial_x u \quad \text{y} \quad -f(x,y) = \partial_y u.
$$

Veamos que efectivamente $u$ es constante a lo largo de las trayectorias
$$
\frac{d}{dt}u(x(t),y(t)) = x'\partial_xu + y'\partial_yu = f(x,y)g(x,y) - g(x,y)f(x,y) = 0.
$$
:::

---

:::{.example}
Un función $f = (u(x,y),v(x,y)):\mathbb{C}\to\mathbb{C}$ es **holomorfa** si satisface las **ecuaciones de Cauchy-Riemann**
$$
\partial_x u = \partial_y v, \qquad \partial_y u = - \partial_x v.
$$
Estas implican que $u$ y $v$ son funciones armónicas
$$
(\partial_x^2+\partial_y^2)u=(\partial_x^2+\partial_y^2)v=0,
$$
y adicionalmente sus conjuntos de nivel son ortogonales entre si. Sus gradientes son exactamente rotaciones de 90 grados uno del otro.

Dada una función armónica $u:\mathbb{C}\to\mathbb R$, es posible construir una función armónica $v$ tal que $Dv = (-\partial_y u,\partial_x u)$. Estas se conocen como los conjugados armónico de $u$. Cualesquiera dos conjugados de la misma función $u$ difieren por una constante.

Por ejemplo, tomemos la función armónica $u(x,y) = x^2-y^2$. Debemos así resolver $\partial_x v = 2y$ y $\partial_y v=2x$. De la primera ecuación obtenemos $v = 2xy+\varphi(y)$ y por lo tanto $2x=2x+C'(y)$ lo cual implica que $C$ es constante. Concluímos así que $v(x,y) = 2xy+C$ es el conjungado armónico de $u$.
:::

---

:::{.exercise}
Calcula el conjugado armónico de las siguientes funciones:

- $u(x,y) = x^3-3xy^2$,

- $u(x,y) = e^{x}\cos y$,

- $u(x,y) = \ln(x^2+y^2)$.
:::

<details>
<summary>Solución</summary>
</details>

---

En general, dado un campo vectorial $v$, la derivada
$$
D_vu = \partial_tu+ v \cdot Du
$$
se conoce como la **derivada material** de $u$ y describe la tasa de cambio de $u$ a lo largo de las trayectorias generadas por $v$.

## Problemas no-homogéneos

Puede darse también el caso de que la función $u$ no sea necesariamente constante a lo largo de las trayectorias de la EDO $x'=v(x)$, pero que sin embargo sus variaciones sean conocidas en función de la posición en la trayectoria.

---

:::{.example}
Si $u(x_0)$ denota el tiempo que tarda la trayectoria que parte de la posición inicial $x_0$ en llegar a un dado conjunto $F$, entonces a lo largo de una solución $z(t) := u(x(t))$ tiene derivada igual a $-1$. Es decir que satisface la ecuación no-homogénea
$$
v\cdot Du = -1.
$$
:::

---

En general podemos aplicar un razonamiento similar a la ecuación no-homogénea
$$
v\cdot Du = f(x).
(\#eq:eq2)
$$
La ecuación característica de \@ref(eq:eq2) sigue siendo $x'=v(x)$, sin embargo $z(t) = u(x(t))$ ahora no es constante a lo largo de una curva característica. En cambio $z$ satisface $z'=f(x)$. Podemos decir así que las ecuaciones características están dadas en verdad por un sistema débilmente acoplado
$$
\begin{cases}
x'= v(x),\\
z' = f(x).
\end{cases}
$$

Se dice que es débilmente acoplado porque por lo menos la ecuación $x'=v(x)$ es independiente de $z$. Para resolver el sistema uno puede comenzar resolviendo el problema para $x$ y luego substituir este resultado en la ecuación para $z$ la cual se puede resolver por medio de una integración
$$
z(t) = z_0 + \int_{0}^t f(x(s))ds.
$$

---

:::{.exercise}
Calcula el tiempo que se toma la curva $(x(t),y(t))$ que parte de $(x_0,y_0)$ en llegar a $F=\{y=0,x\geq0\}$ si esta se mueve según la ecuación diferencial
$$
x'=-y, \qquad y'=x.
$$
Usa esta información para resolver
$$
y\partial_xu-x\partial_yu=1 \text{ en } \mathbb R^2\setminus F,\\
u=0 \text{ en } F
$$
¿Tiene sentido que $u$ sea discontinua en $F$?
:::

<details>
<summary>Solución</summary>
</details>

## Problemas semi-lineales

Generalizando la idea de las ecuaciones no-homogéneas, puede darse el caso de que las variaciones de $z(t) = u(x(t))$ dependan de $x$ y también de la misma $z=u(x)$. Por ejemplo, la ecuación $z'=-cz$ aparece cuando $z$ representa una ganancia descontada con taza $c$ que se obtiene cuando la trayectoria llega a una dada región $F$.

Consideremos la ecuación
$$
v\cdot Du = f(u,x).
$$
Se dice que es **semi-lineal** dado que el operador asociado a las derivadas de orden mayor (en este caso uno) es lineal y solamente depende de $x$, sin embargo el problema puede presentar combinaciones no-lineales en $u$ dadas por $f$.

Las ecuaciones características vuelven a ser un sistema débilmente acoplado dado por
$$
\begin{cases}
x'= v(x),\\
z' = f(z,x).
\end{cases}
$$
En este caso, también se puede proceder resolviendo primero la ecuación para $x$ y sustituyendo el resultado en la ecuación para $z$. Sin embargo, el último paso requiere resolver una ecuación no-homogénea para $z$ y no simplemente calcular una integral.

---

:::{.exercise}
Dado el campo vectorial $v=(ax+by,cx+dy)$ en el plano, resuelve el problema de valores iniciales
$$
\begin{cases}
\partial_t u + \operatorname{div}(vu) =0 \text{ en }\mathbb R^2\times (0,\infty),\\
u=u_0 \text{ en } \{t=0\}
\end{cases}
$$
Demuestra que si $\int_{\mathbb R^2}u_0(x,y)dxdy<\infty$, entonces $m(t) = \int_{\mathbb R^2}u(x,y,t)dxdy$ permanece constante.
:::

<details>
<summary>Solución</summary>
</details>

## Problemas cuasi-lineales

Finalmente consideramos el caso donde el campo $v$ también depende de $u$. Esto hace que la EDO y la EDP estén estrechamente acopladas.

---

:::{.example}
La ecuación de **Burgers** modela la ley de inercia de un fluído (incompresible y de densidad uniforme) con velocidad $u(x,t)$ en la posición $x \in \mathbb R$ y en tiempo $t \in \mathbb R$. Para decir que el momento es una cantidad conservada a lo largo del flujo usamos que
$$
\partial_t u + u \partial_x u =0.
$$
:::

---

En el caso general
$$
v(u,x)\cdot Du = f(u,x)
$$
decimos que la ecuación es **cuasi-lineal**. Esto quiere decir que el operador asociado a las derivadas de orden mayor es lineal, pero puede depender en este caso de $u$. Como es de esperarse la ecuación característica es ahora un sistema fuertemente acoplado
$$
\begin{cases}
x'= v(z,x),\\
z'=f(z,x).
\end{cases}
$$

---

:::{.exercise}
¿Qué relación guarda la ecuación de Burgers (EDP: $\partial_t u + u \partial_x u =f$) con la ley de Newton (EDO: $x'' = f$)?
:::

<details>
<summary>Solución</summary>
</details>

---

En los casos de las ecuaciones semi-lineales encontramos que las curvas características que se corresponden a la ecuación $x'=v(x)$ fibran el dominio, es decir lo cubren de forma disjunta bajo hipótesis regularidad y crecimiento para el campo vectorial.

El caso de las ecuaciones características para problemas estrictamente cuasi-lineales, es decir de la forma
$$
\begin{cases}
x'= v(z,x),\\
z'=f(z,x),
\end{cases}
$$
es radicalmente distinto. El teorema de unicidad garantiza que las trayectorias son disjuntas, ***pero en el sistema de coordenadas $(x,z)$***, las proyecciones en el hiper-plano de las $x$'s ***puede tener intersecciones***. Esto implica que las soluciones de la EDP pasan a ser funciones multi-valuadas. En la práctica decimos que las soluciones están definidas hasta el primer momento en que ocurre una colisión en las características.

---

:::{.exercise}
Encuentra el valor más grande posible para $T$ tal que el siguiente problema de valores iniciales tiene solución en el intervalo $[0,T)$
$$
\begin{cases}
\partial_tu + u\partial_x u = -\sin x \text{ en } \mathbb R\times(0,T)\\
u=0 \text{ en } \{t=0\}
\end{cases}
$$
:::

<details>
<summary>Solución</summary>
</details>