# (PART\*) Métodos espectrales {-}

# Espectro

Cualesquiera de las tres ecuaciones funcdamentales para el Laplaciano (Poisson, difusión y onda) pueden ser resueltas si conocemos una descomposición de los datos en términos de autofunciones del Laplaciano. La teoría extiende las ideas ya expuestas en el capítulo [discreto](#espectro-del-laplaciano). Las justificaciones rigurosas en esta dirección fueron las que motivaron la teoría de análisis de Fourier y el análisis moderno en los siglos diecinueve y veinte. Recomendamos la introducción de [Fourier Analysis: An Introduction](https://press.princeton.edu/books/hardcover/9780691113845/fourier-analysis) por Elias Stein y Rami Shakarchi para obtener un panorama histórico del desarrollo y motivaciones detrás de la teoría.

<iframe width="560" height="315" src="https://www.youtube.com/embed/xWMCgg57MiA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Resolución de distintos problemas usando el espectro

Por fijar algunas ideas tomemos un operador lineal $A:V\to V$ con una base de autovectores ortogonales $\{\xi_k\}$ (respecto a algún producto interno o hermitiano $\langle\cdot,\cdot\rangle$) y sus correspondientes autovalores serán denotados por $\{\lambda_k\}$.

### Inversa

Para la ecuación $Ax=b$ tenemos que si $b = \sum_k \hat b_k\xi_k$ y cero no es un autovalor de $A$, entonces podemos encontrar una solución de la forma $x = \sum_k \hat x_k\xi_k$ igualando los coeficientes al substituir estas expresiones en la ecuación
$$
\sum_k \hat b_k\xi_k = b = Ax= \sum_k \hat x_k A\xi_k = \sum_k \hat x_k \lambda_k\xi_k \qquad\Rightarrow\qquad \hat x_k = \frac{\hat b_k}{\lambda_k}.
$$
Para calcular $\hat b_k$ usamos la ortogonalidad de los autovectores, de forma que la tomar el producto punto de $\xi_j$ y $b = \sum_k \hat b_k\xi_k$ obtenemos la fórmula para los coeficientes de Fourier
$$
\hat b_j = \frac{\langle b, \xi_j\rangle}{\|\xi_j\|^2}.
$$
Sintetizando esta información para la solución obtenemos que^[Dados dos vectores $a$ y $b$ en un espacio vectorial $V$ con producto interno $\langle\cdot,\cdot\rangle$, definimos $a\otimes b: V\to V$ como $(a\otimes b)(v) = \langle v,b\rangle a$. Si $V=\mathbb R^n$ con el producto punto entonces $a\otimes b$ se identifica con la matriz con componentes $a_ib_j$ en la fila $i$, columna $j$. En el caso particular donde $a=b=\xi\neq 0$ tenemos que $\xi\otimes\xi/\|\xi\|^2$ es la proyección ortogonal sobre la recta generada por $\xi$.]
$$
x = \sum_k \frac{1}{\lambda_k}\frac{\langle b, \xi_k\rangle}{\|\xi_k\|^2}\xi_k = \sum_k \frac{1}{\lambda_k}\frac{\xi_k\otimes \xi_k}{\|\xi_k\|^2} b.
$$
En particular, si $\{\xi_k\}$ genera el espacio vectorial encontramos que $A$ es invertible y
$$
A^{-1} = \sum_k \frac{1}{\lambda_k}\frac{\xi_k\otimes \xi_k}{\|\xi_k\|^2}.
$$
Para el problema Dirichlet con dato de borde cero, el inverso del Laplaciano se conoce como la **función de Green**.

### Exponencial

En el caso del sistema lineal de EDOs con coeficientes constantes $x'=Ax+f(t)$ tenemos que según la teoría de EDOs lineales
$$
x(t) = \exp(At)x(0)+\int_0^t \exp(A(t-s))f(s)ds.
$$
Para calcular el resultado de aplicar la exponencial a un vector dado, es decir $y(t) = \exp(At)y(0)$, procedemos con un análisis similar a partir de una descomposición $y(t) = \sum_k \hat y_k(t)\xi_k$. La idea es que $y'=Ay$ se diagonaliza en la base de autovectores
$$
\sum_k \hat y_k'(t)\xi_k = \sum_k \lambda_k\hat y_k(t)\xi_k \qquad \Rightarrow\qquad \hat y_k' = \lambda_k\hat y_k \qquad \Rightarrow\qquad \hat y_k(t) = e^{\lambda_k t}\hat y_k(0)
$$
Sintetizando en
$$
\begin{aligned}
\exp(At)y(0) &= y(t),\\
&= \sum_k \hat y_k(t)\xi_k,\\
&= \sum_k e^{\lambda_k t}\hat y_k(0)\xi_k,\\
&= \sum_k e^{\lambda_k t}\frac{\langle y(0),\xi_k\rangle}{\|\xi_k\|^2}\xi_k,\\
&= \left(\sum_k e^{\lambda_k t}\frac{\xi_k\otimes \xi_k}{\|\xi_k\|^2} \right)y(0).
\end{aligned}
$$
Descubrimos así que
$$
\exp(At) = \sum_k e^{\lambda_k t}\frac{\xi_k\otimes \xi_k}{\|\xi_k\|^2}.
$$
Observamos que en este caso no hizo falta asumir que cero no es un autovalor.

Para el Laplaciano esta exponencial se conoce como el **núcleo del calor**. Recordemos que los autovalores del Laplaciano en el caso discreto eran menores o iguales a cero, y anticipamos que lo mismo ocurre en el caso continuo. Es decir que para las soluciones de la ecuación del calor obtenemos decaimiento exponencial de cada uno de los términos en la serie (a menos que cero sea un autovalor).

### Funciones trigonométricas

Finalmente en el caso de la ecuación de segundo orden $x'' = Ax+f(t)$ tenemos que
$$
x(t) = \cos(At)x(0) + t\operatorname{sinc}(At)x'(0) + \int_0^t (t-s)\operatorname{sinc}(A(t-s))f(s)ds.
$$
Donde al igual que con la exponencial podemos definir las funciones exponenciales a partir de sus series de Taylor alrededor del cero
$$
\cos(At) := \sum_{k=0}^\infty \frac{(-1)^k}{(2k)!}(At)^{2k}, \qquad \operatorname{sinc}(At) := \sum_{k=0}^\infty \frac{(-1)^k}{(2k+1)!}(At)^{2k}.
$$
(Si $At$ es invertible $\operatorname{sinc}(At) = \sin(At)(At)^{-1}$). Como es de esperarse se satisfacen las identidades trigonométricas usuales, por ejemplo
$$
\frac{d}{dt}\cos(At) = -A^2 t \operatorname{sinc}(At), \qquad \frac{d}{dt}(t\operatorname{sinc}(At)) = \cos(At).
$$

Al igual que antes podemos dar fórmulas para $\cos(At)$ y $\operatorname{sinc}(At)$ cuando $A$ tiene una base ortogonal de autovectores
$$
\cos(At) = \sum_k \cos(\lambda_k t)\frac{\xi_k\otimes \xi_k}{\|\xi_k\|^2}, \qquad \operatorname{sinc}(At) = \sum_k \operatorname{sinc}(\lambda_k t)\frac{\xi_k\otimes \xi_k}{\|\xi_k\|^2}.
$$

### Cálculo funcional

En general podemos definir para ciertas funciones su efecto en un operador lineal usando la descomposición espectral. Formalmente tenemos una combinación de distintas proyecciones ortogonales sobre los autovectores de $A$
$$
f(A) := \sum_k f(\lambda_k) \frac{\xi_k\otimes \xi_k}{\|\xi_k\|^2}.
$$
Si $f$ tiene una serie de potencias absolutamente convergente en la recta real (el caso de la exponencial y las funciones trigonométricas),
$$
f(x) = \sum_{k=0}^\infty f_kx^k,
$$
entonces podemos definir $f(A)$ equivalentemente usando la misma serie
$$
f(A) = \sum_{k=0}^\infty f_kA^k.
$$
Gracias a la convergencia absoluta de $f(x)$ tenemos la convergencia absoluta de $f(A)$ con respecto a la [**norma de operador**](https://en.wikipedia.org/wiki/Operator_norm)
$$
\sum_{k=0}^\infty \|f_kA^k\| \leq 
\sum_{k=0}^\infty |f_k|\|A\|^k < \infty.
$$
Por lo tanto estas series pueden ser diferenciadas, integradas, y multiplicadas tal como si fueran polinomios. A partir de acá se deducen distintas identidades para las exponenciales o funciones trigonométricas actuando sobre operadores.

## Casos unidimensionales para el Laplaciano

### Segmento con dato de borde cero

Sea $(0,L)$ un segmento de la recta real. Buscamos diagonalizar el Laplaciano, es decir la segunda derivada, bajo la restricción de que las autofunciones se anuulan en los extremos $0$ y $L$. Es decir
$$
\begin{cases}
\phi''= -\lambda \phi \text{ en } (0,L),\\
\phi(0) = \phi(L) = 0.
\end{cases}
$$

De la ecuación obtenemos que
$$
\phi(x) = \begin{cases}
A_+e^{\sqrt{-\lambda} x}+A_-e^{-\sqrt{-\lambda} x} \text{ si }\lambda <0,\\
A_++A_-x \text{ si }\lambda =0,\\
A_+\cos(\sqrt{\lambda}x)+A_-\sin(\sqrt{\lambda}x) \text{ si }\lambda >0.
\end{cases}
$$
De estas opciones solamente la tercera permite que se satisfaga $\phi(0)=\phi(L)=0$ cuando $\phi$ es un múltiplo de $\sin(\pi k x/L)$. Definimos así
$$
\phi_k(x) = \sin\left(\frac{\pi k}{L}x\right), \qquad \lambda_k = \left(\frac{\pi k}{L}\right)^2,
$$
tal que $\phi_k''=-\lambda_k\phi_k$.

Observamos además que $\lambda_k = \lambda_{-k} > 0$ para $k\geq 1$, $\lambda_0=0$, y $\phi_{-k}=-\phi_k$. Es decir que existe por lo menos chance de que $\{\phi_k\}_{k\geq1}$ sean una base. De hecho son linealmente independientes gracias a la siguiente observación de ortogonalidad.

---

:::{.exercise}
Demuestra que las funciones $\{\phi_k\}_{k\geq1}$ satisfacen
$$
\int_0^L \phi_k\phi_j = \begin{cases}
0 \text{ si } k\neq j,\\
L/2 \text{ si } k=j.
\end{cases}
$$
:::

<details>
<summary>**Solución**</summary>
Una posible solución se obtiene usando la identidad trigonométrica
$$
2\sin\alpha\sin\beta = \cos(\alpha-\beta)-\cos(\alpha+\beta).
$$
Otra solución se obtiene integrando por partes (dos veces).
</details>

---

No solamente son las funciones $\{\phi_k\}_{k\geq1}$ linealmente independientes, estas también generan las funciones sobre $(0,L)$. Para dar sentido a esta afirmación es necesario dar una noción de convergencia para series de la forma $\sum_{k=1}^\infty a_k\phi_k$. Esto lo haremos más adelante y de momento asumiremos a las series como sumas formales.

#### Función de Green

Dado $f:(0,L)\to \mathbb R$, buscamos una fórmula para la solución de
$$
\begin{cases}
u''=f\text{ en }(0,L),\\
u(0)=u(L)=0.
\end{cases}
$$
Gracias a la diagonalización que ya conocemos para este problema tenemos que
$$
\begin{aligned}
u(x) &= -\sum_{k=1}^\infty \frac{1}{\lambda_k}\frac{\langle f,\phi_k\rangle }{\|\phi_k\|^2}\phi_k(x),\\
&= -\frac{2L}{\pi^2}\int_0^L \left(\sum_{k=1}^\infty\frac{\sin(\pi k x/L)\sin(\pi ky/L)}{k^2}\right)f(y)dy,\\
&= \int_0^L G(x,y)f(y)dy
\end{aligned}
$$
donde $G$ es la función de Green para $(0,L)$
$$
G(x,y) := -\frac{2L}{\pi^2}\sum_{k=1}^\infty\frac{\sin(\pi k x/L)\sin(\pi ky/L)}{k^2}.
$$

---

:::{.example}
Consideremos el problema
$$
\begin{cases}
u''=1 \text{ en } [0,1],\\
u(0)=u(1)=0.
\end{cases}
$$
Para calcular $u$ como una serie de senos debemos primero calcular la serie de senos de la función constante $1$
$$
\hat f_k = \frac{1}{2}\int_0^1 \sin(k\pi x)dx = \begin{cases}
0 \text{ si } k\equiv 0 \, (\text{mod 2}),\\
4/(k\pi) \text{ si } k\equiv 1 \, (\text{mod 2}).
\end{cases}
$$
Por lo tanto
$$
u(x) =-\sum_{k=1}^\infty \frac{\hat f_k}{\lambda_k}\sin(k\pi x)=-\frac{4}{\pi^3}\sum_{k=1}^\infty \frac{\sin(k\pi x)}{k^3}.
$$
:::

---

Una alternativa más elemental que tenemos para resolver el problema de Poisson en un segmento es integrar $u''=f$ dos veces. Primero
$$
u'(x) = u'(0) + \int_0^x f(y)dy.
$$
Luego y usando que $u(0)=0$,
$$
u(x) = u'(0)x + \int_0^x \int_0^y f(z)dzdy = u'(0)x + \int_0^x \int_z^x f(z)dydz= u'(0)x + \int_0^x f(z)(x-z)dz.
$$
Usando que $u(L)=0$ descubrimos que
$$
u'(0) = -\frac{1}{L}\int_0^L f(z)(L-z)dz,
$$
por lo que,
$$
u(x) = \int_0^x f(z)(x-z)dz - \frac{x}{L}\int_0^L f(z)(L-z)dz = \int_0^L f(z) G(x,z)dz,
$$
donde
$$
G(x,z) = \begin{cases}
x-z-\frac{x}{L}(L-z)\text{ si } z\in[0,x],\\
-\frac{x}{L}(L-z)\text{ si } z\in[x,L].
\end{cases}
$$

---

:::{.example}
Consideremos una vez más el problema
$$
\begin{cases}
u''=1 \text{ en } [0,1],\\
u(0)=u(1)=0.
\end{cases}
$$
Integrando un par de veces encontramos que
$$
u(x) = \frac{x(x-1)}{2}.
$$
Gracias al ejemplo previo obtenemos la curiosa identidad
$$
\sum_{k=1}^\infty \frac{\sin(k\pi x)}{(k\pi)^3} = \frac{x(1-x)}{8}.
$$
Para $x=1/2$ tendríamos que
$$
\sum_{k=0}^\infty \frac{(-1)^k}{(2k+1)^3} = \frac{\pi^3}{32}.
$$
:::

---

Cuando graficamos la función $G(x,\cdot)$ notamos que es continua y afín a trozos.

<iframe src="https://www.geogebra.org/graphing/xk4yrywc?embed" width="800" height="600" allowfullscreen style="border: 1px solid #e4e4e4;border-radius: 4px;" frameborder="0"></iframe>

Observemos que además la diferencia entre las dos pendientes es siempre uno, lo cual sirve para descomponer a $G$ como $|z-x|/2$ más una función afín para que se cumplan que $G(x,0)=G(x,L)=0$. Es decir
$$
G(x,z) = \frac{1}{2}|z-x| - \left(\frac{L-z}{2L}x+\frac{z}{2L}(L-x)\right) = \frac{L|z-x|-(L-z)x-z(L-x)}{2L}.
$$

Ahora que finalmente tenemos dos expresiones para la función de Green deducimos una curiosa identidad ($L=1$, $x,y\in[0,1]$)
$$
\frac{1}{\pi^2}\sum_{k=1}^\infty\frac{\sin(\pi k x)\sin(\pi ky)}{k^2} = \frac{(1-y)x+y(1-x)-|y-x|}{4}.
$$
En particular, si $x=y=1/2$ recuperamos la identidad de Euler
$$
\sum_{k=0}^\infty \frac{1}{(2k+1)^2} = \frac{\pi^2}{8}.
$$

#### Núcleo del calor

En este caso no tenemos una fórmula cerrada para el núcleo dado por la siguiente serie
$$
H(x,t,y) := \frac{2}{L}\sum_{k=1}^\infty e^{-(k\pi/L)^2t}\sin(k\pi x/L)\sin(k\pi y/L).
$$
Recordemos que a partir de $H$ calculamos las soluciones de
$$
\begin{cases}
\partial_t u = \partial_x^2 u \text{ en } (0,L)\times(0,\infty),\\
u(0,t)=u(L,t)=0 \text{ para } t \geq 0,\\
u(x,0) = u_0(x) \text{ para } x \in [0,L].
\end{cases}
$$
usando la fórmula de representación
$$
u(x,t) = \int_0^L H(x,t,y)u_0(y)dy.
$$

---

:::{.example}
Usando que $u(x,t)=x(1-x)-2t$ satisface la ecuación de calor en $(0,1)$ con dato de borde cero, y la serie de senos para la condición inicial $x(1-x)$ de un ejemplo previo, tenemos que
$$
\sum_{k=1}^\infty \frac{e^{-(k\pi)^2t}}{(k\pi)^3}\sin(k\pi x) = \frac{x(1-x)-2t}{16}.
$$
:::

---

Una hermosa introducción a estas ideas está presentada en el siguiente video de 3 Blue 1 Brown:

<iframe width="560" height="315" src="https://www.youtube.com/embed/ToIXSwZ1pJU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

#### Ecuación de onda

En este caso tampoco contamos con una fórmula cerrada para el núcleo
$$
C(x,t,y) := \frac{2}{L} \sum_{k=1}^\infty \cos(k\pi t/L)\sin(k\pi x/L)\sin(k\pi y/L).
$$
Recordemos que a partir de $C$ calculamos las soluciones de
$$
\begin{cases}
\partial_t^2 u = \partial_x^2 u \text{ en } (0,L)\times(0,\infty),\\
u(0,t)=u(L,t)=0 \text{ para } t \geq 0,\\
u(x,0) = u_0(x) \text{ para } x \in [0,L],\\
\partial_t u(x,0) = 0 \text{ para } x \in [0,L].
\end{cases}
$$
usando la fórmula de representación
$$
u(x,t) = \int_0^L C(x,t,y)u_0(y)dy.
$$

Si en cambio tenemos a la mano el problema
$$
\begin{cases}
\partial_t^2 u = \partial_x^2 u \text{ en } (0,L)\times(0,\infty),\\
u(0,t)=u(L,t)=0 \text{ para } t \geq 0,\\
u(x,0) = 0 \text{ para } x \in [0,L],\\
\partial_t u(x,0) = v_0(x) \text{ para } x \in [0,L].
\end{cases}
$$
entonces
$$
u(x,t) = \int_0^L S(x,t,y)v_0(y)dy,
$$
donde
$$
S(x,t,y) := \frac{2}{L}\sum_{k=1}^\infty \frac{\sin(k \pi t/L)}{k\pi/L}\sin(k\pi x)\sin(k\pi y).
$$

En el caso un poco más general
$$
\begin{cases}
\partial_t^2 u = \partial_x^2 u \text{ en } (0,L)\times(0,\infty),\\
u(0,t)=u(L,t)=0 \text{ para } t \geq 0,\\
u(x,0) = u_0(x) \text{ para } x \in [0,L],\\
\partial_t u(x,0) = v_0(x) \text{ para } x \in [0,L].
\end{cases}
$$
usamos la superposición
$$
u(x,t) = \int_0^L C(x,t,y)u_0(y)dy+\int_0^L S(x,t,y)v_0(y)dsdy.
$$

---

:::{.exercise}
Calcula la fórmula de representación para el problema de onda no homogéneo
$$
\begin{cases}
\partial_t^2 u = \partial_x^2 u +f(x,t) \text{ en } (0,L)\times(0,\infty),\\
u(0,t)=u(L,t)=0 \text{ para } t \geq 0,\\
u(x,0) = u_0(x) \text{ para } x \in [0,L],\\
\partial_t u(x,0) = v_0(x) \text{ para } x \in [0,L].
\end{cases}
$$
en términos de los núcleos $C$ y $S$.
:::

<details>
<summary>**Solución**</summary>
$$
u(x,t) = \int_0^L C(x,t,y)u_0(y)dy+\int_0^L S(x,t,y)v_0(y)dy + \int_0^t \int_0^L S(x,t-s,y)f(y,s)dyds.
$$
</details>

### Circunferencia o funciones periódicas

Las autofunciones periódicas de la ecuación $\phi''=-\lambda \phi$ en $\mathbb R/2L\mathbb Z$ toman necesariamente la forma
$$
\phi_k(x) := e^{ik\pi x/L}.
$$
El autovalor asociado es así
$$
-\lambda_k = -\left(\frac{k\pi}{L}\right)^2.
$$

Tenemos la relación de ortogonalidad
$$
\int_{-L}^L \phi_k(x)\overline{\phi_j(x)}dx = \int_{-L}^L e^{i(k-j)\pi x/L}dx =\begin{cases}
0 \text{ si } k\neq j,\\
2L \text{ si } k=j.
\end{cases}
$$
Por lo tanto tenemos la siguiente fórmula para los **coeficientes de Fourier**
$$
\hat f_k := \frac{\langle f,\phi_k\rangle}{\|\phi_k\|^2} = \frac{1}{2L}\int_{-L}^L f(x)e^{-ik\pi x/L}dx.
$$

## Propiedades de la serie de Fourier

Sea $L>0$ y consideremos funciones $2L$-periódicas en $\mathbb R$. Usualmente usaremos el intervalo $[-L,L)$ como una ventana representativa para el dominio de una de estas funciones.

Tenemos la base de Fourier compleja numerada por los enteros
$$
\phi_k(x) := e^{ik\pi x/L}.
$$

Recordemos que si $f$ se descompone como
$$
f = \sum_{k=-\infty}^\infty \hat f_k \phi_k
$$
entonces por la ortogonalidad de la base
$$
\hat f_k = \frac{1}{2L}\int_{-L}^L f(x)e^{-ik\pi x/L}dx.
$$
Asumiremos que todas las funciones con las que trabajamos en esta sección admiten una de estas descomposiciones.

---

:::{.example}
Si $f=1$ tenemos que $\hat f_k=1$ si $k=0$ y cero en cualquier otro caso.
:::

---

:::{.example}
Si $\hat f_k=1$ para $k=k_0$ y cero en cualquier otro caso, entonces $f(x) = e^{ik_0\pi x/L}$. Si en cambio $\hat f_k=1$ para $k=\pm k_0$ y cero en cualquier otro caso, entonces $f(x) = 2\cos(k_0\pi x/L)$. Finalmente si $\hat f_k=1$ para $k=k_0$,$\hat f_k=-1$ para $k=-k_0$, y cero en cualquier otro caso, entonces $f(x) = 2i\sin(k_0\pi x/L)$.
:::

---

:::{.exercise}
Demuestra que si $f$ es una función real y $2L$-periódica, entonces
$$
\overline{\hat f_k} = \hat f_{-k}
$$
:::

<detalis>
<summary>**Solución**</summary>
Basta usar que $\bar f = f$ en la descomposición de $f$
</details>

### Linealidad

Claramente la transformación que arroja los coeficientes de Fourier satisface el principio de superposición. Es decir que para constantes $\alpha$, $\beta$, y funciones $f$ y $g$
$$
(\alpha f +\beta g)^\wedge_k = \alpha \hat f_k + \beta \hat g_k.
$$

### Traslaciones

Sea $\tau \in \mathbb R$ y $f_\tau(x) := f(x-\tau)$, es decir que la gráfica de $\f_\tau$ es la gráfica de $f$ trasladada $|\tau|$ unidades a la derecha si $\tau\geq 0$ (o a la izquierda si $\tau<0$). El efecto de una traslación horizontal en los coeficientes de Fourier es una modulación de los coeficientes
$$
\begin{aligned}
(f_\tau)_k^\wedge &= \frac{1}{2L}\int_{-L}^L f(x-\tau)e^{-ik\pi x/L}dx,\\
&= \frac{1}{2L}\int_{-L}^L f(x)e^{-ik\pi (x+\tau)/L}dx,\\
&= e^{-ik\pi \tau/L}\hat f_k.
\end{aligned}
$$

---

:::{.example}
Sea $L=\pi$. Dado que $\sin=\cos_{\pi/2}$ tenemos que
$$
\sin_k^\wedge = e^{-ik \pi/2}\cos_k^\wedge = (-i)^k \cos_k^\wedge.
$$
En particular, como sabemos que $\cos_k^\wedge = 1/2$ para $k=\pm 1$, siendo cero en los demás casos, recuperamos que $\sin_1^\wedge=-i/2$ y $\sin_1^\wedge=i/2$, y cero en los demás casos.
:::

---

:::{.exercise}
Demuestra que si $g(x) = f(x)e^{i\pi x/L}$, es decir una modulación de $f$, entonces
$$
\hat g_k = \hat f_{k-1} \qquad (\text{una traslación de los coeficientes}).
$$
:::

<details>
<summary>**Solución**</summary>
</details>

### Derivadas

Para calcular los coeficientes de la derivada a partir de los coeficientes originales usamos la fórmula de integración por partes
$$
\begin{aligned}
(f')_k^\wedge &= \frac{1}{2L}\int_{-L}^L f'(x)e^{-ik\pi x/L}dx,\\
&= \frac{ik\pi}{2L^2}\int_{-L}^L f(x)e^{-ik\pi x/L}dx,\\
&= \frac{ik\pi}{L}\hat f_k.
\end{aligned}
$$
También es una fórmula que puede ser deducida a partir de la identidad de la traslación y la linealidad
$$
\begin{aligned}
(f')_k^\wedge &= \lim_{\tau\to 0} \frac{\hat f_k-(f_\tau)^\wedge_k}{\tau} = \lim_{\tau\to 0} \frac{1-e^{-ik\pi \tau/L}}{\tau} \hat f_k = \frac{ik\pi}{L}\hat f_k.
\end{aligned}
$$

---

:::{.exercise}
Demuestra la propiedad de traslación a portir de la identidad de la derivada.
:::

<details>
<summary>**Solución**</summary>
</details>

### Convoluciones

Otra consecuencia de la propiedad de la traslación es la propiedad de la convolución. Consideremos las tralaciones de una función dada $f$ y promediemos estas con respecto a un peso también $2L$-periódico. Como resultado tenemos la función periódica
$$
(f\ast g)(x) := \int_{-L}^L f(x-\tau)g(\tau)d\tau.
$$

---


:::{.example}
Para $L=\pi$
$$
\begin{aligned}
(\cos\ast\cos)(x) &= \int_{-\pi}^\pi \cos(x-\tau)\cos \tau d\tau,\\
&= \cos x \int_{-\pi}^\pi \cos^2 \tau d\tau + \sin x\int_{-\pi}^\pi \sin \tau \cos \tau d\tau,\\
&= \pi \cos x.
\end{aligned}
$$
:::

---

Esta operación es claramente bilineal y simétrica
$$
f\ast g = g\ast f.
$$

---

:::{.exercise}
Demuestra que la convolución satisfaces la ley asociativa
$$
(f\ast g)\ast h = f\ast (g\ast h).
$$
:::

<details>
<summary>**Solución**</summary>
Es consecuencia de la identidad de Fubini.
</details>

---

Para los coeficientes de Fourier tenemos gracias a Fubini que

$$
\begin{aligned}
(f\ast g)_k^\wedge &= \hat f_k\int_{-L}^L e^{-ik\pi \tau/L} g(\tau) d\tau = 2L\hat f_k\hat g_k.
\end{aligned}
$$

---

:::{.example}
Para $L=\pi$ tenemos que $\cos_k^\wedge=1/2$ si $k=\pm 1$ y cero en cualquier otro caso. El ejercicio previo donde calculamos $\cos\ast \cos = \pi\cos$ es consistente con la propiedad de la convolución dado que
$$
(\cos\ast \cos)_1^\wedge = 2\pi(\cos_1^\wedge)^2 = \pi/2 = (\pi\cos)_1^\wedge.
$$
:::

---

:::{.exercise}
Justifica por qué
$$
(fg)_k^\wedge = \sum_{\tau =\infty}^\infty \hat f_{k-\tau}\hat g_\tau
$$
:::

<details>
<summary>**Solución**</summary>
Asumiendo que las series convergen y pueden ser reordenadas
$$
\begin{aligned}
(fg)(x) &= \left(\sum_{k=-\infty}^\infty \hat f_ke^{-ik\pi x/L}\right)\left(\sum_{k=-\infty}^\infty \hat g_ke^{-ik\pi x/L}\right),\\
&= \sum_{j,k=-\infty}^\infty \hat f_j\hat g_k e^{-i\pi(j+k)x/L},\\
&= \sum_{k=-\infty}^\infty \left(\sum_{\tau=-\infty}^\infty \hat f_{k-\tau}\hat g_\tau\right)e^{-i\pi k x/L}.
\end{aligned}
$$
</details>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The Fourier transform diagonalizes convolution operators aka circulant matrices aka linear operators which commute with translations. <br>The foundation of linear signal processing. <a href="https://t.co/A8RlE7BTFe">https://t.co/A8RlE7BTFe</a> <a href="https://t.co/4Hy50BBcqI">pic.twitter.com/4Hy50BBcqI</a></p>&mdash; Gabriel Peyré (@gabrielpeyre) <a href="https://twitter.com/gabrielpeyre/status/1577886370634371073?ref_src=twsrc%5Etfw">October 6, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 

### Isometría

Los coeficientes de Fourier se pueden entender como una transformación de cambio de base del espacio de funciones periódicas con el producto hermitiano dado por
$$
\langle f,g\rangle = \int_{-L}^L f(x)\overline{g(x)}dx.
$$
a las sucesiones indexadas por los enteros.

El espacio de funciones se denota usualmente por
$$
L^2(\mathbb R/2L\mathbb Z\to \mathbb C) := \left\{f:\mathbb R/2L\mathbb Z\to \mathbb C \ | \ \int_{-L}^L |f|^2 < \infty\right\},
$$
y podemos abreviarlo por $L^2$. El espacio de sucesiones se denota por
$$
\ell^2(\mathbb Z) := \left\{(f_k)_{k\in \mathbb Z} \ | \ \sum_k |f_k|^2<\infty\right\},
$$
y también puede ser abreviado como $\ell^2$. Este espacio de funciones también cuenta con un producto hermitiano que extiende el producto de $\mathbb C^n$
$$
\langle (f_k),(g_k)\rangle= \sum_k f_k\overline{g_k}.
$$
La razón por la cual pedimos que las funciones y las series sean cuadrado integrables o sumables es para que la norma definidas por estos productos sean acotadas. Esto implica que las integrales y series involucradas en los productos hermitianos son absolutamente convergentes.

Recordemos que $\{\phi_k(x) = e^{ik\pi x/L}\}$ es una base ortogonal en $L^2$, esto quiere decir que módulo una dilatación $\wedge:L^2\to\ell^2$ es una isometría.

:::{.theorem name="Parseval"}
$$
\langle (\hat f_k),(\hat g_k)\rangle = \sum_k \hat f_k\overline{\hat g_k} = \frac{1}{2L}\int_{-L}^L f\bar g = \frac{1}{2L}\langle f,g\rangle
$$
:::

:::{.proof}
$$
\begin{aligned}
\frac{1}{2L}\int_{-L}^L f\bar g &= \frac{1}{2L}\int_{-L}^L\left(\sum_{k} \hat f_k \phi_k\right)\overline{\left(\sum_{k} \hat g_k \phi_k\right)},\\
&= \frac{1}{2L}\sum_{j,k} \hat f_k\overline{\hat g_j}\langle \phi_k,\phi_j\rangle,\\
&= \sum_k \hat f_k\overline{\hat g_k}.
\end{aligned}
$$
:::

## Productos: Rectángulo y la superficie del toro

## Bola bidimensional

## Esfera tridimensional