# (PART\*) Fórmulas de representación {-}

# Problemas unidimensionales

Sea $D=d/dx$ y sea $L = D^2+2bD+c$ un operador diferencial de segundo orden y con coeficientes constantes. Sabemos que las soluciones del problema homogéneo $Lu=0$ están dadas en función de las raíces del polinomio característico $r_\pm := -b\pm \sqrt{b^2-c}$. Si $b^2\neq c$ entonces las soluciones se escriben en términos de exponenciales (complejas)
$$
u(x) = A_+e^{r_+ t} + A_-e^{r_- t}.
$$
Si en cambio $b^2=c$, entonces $r=r_+=r_-$ y
$$
u(x) = (A+Bt)e^{rt}.
$$

Cuando consideramos el problema no homogéneo $Lu=f$ las soluciones se escriben como la suma de una solución homogénea y una particular que se escribe en términos de una convolución
$$
U(x) = \int_{0}^x K(y)f(x-y)dy = \int_{0}^x K(x-y)f(y)dy.
$$
El núcleo $K$ se calcula como la solución del problema homogéneo
$$
LK= 0, \qquad K(0)=0, \qquad K'(0)=1.
$$

---

:::{.example}
La solución del péndulo forzado ($\omega >0$)
$$
u'' + \omega^2 u = f(t), \qquad u(0)=u_0, \qquad v(0) = v_0
$$
está dado por la fórmula de representación
$$
u(x) = u_0\cos(\omega t) + \frac{v_0}{\omega}\sin (\omega t) + \frac{1}{\omega}\int_0^t \sin(\omega s)f(t-s)ds.
$$
:::

---

El siguiente ejemplo aparece también en la discusión de la [Función de Green](#función-de-green) usando métodos espectrales.

:::{.example}
La solución de la ecuación de Poisson
$$
u'' = f(x), \qquad u(0)=u(1)=1.
$$
Está dada por
$$
u(x) = Ax + \int_0^x (x-y)f(y)dy.
$$
La constante $A$ se escoge de forma que $u(1)=0$, es decir
$$
A = -\int_0^1 (1-y)f(y)dy.
$$
Por lo tanto
$$
u(x) = -x\int_0^1 (1-y)f(y)dy + \int_0^x (x-y)f(y)dy = \int_0^1 K(x,y)f(y)dy
$$
donde
$$
K(x,y) = \begin{cases}
-x(1-y) + (x-y) \text{ si } y \in[0,x],\\
-x(1-y) \text{ si } y \in[x,1].
\end{cases}
$$
lo cual se simplifica a
$$
K(x,y) = \frac{|y-x| + (1-x)y+x(1-y)}{2}.
$$
:::

---

:::{.exercise}
Calcula el núcleo $K$ tal que
$$
u(x) := \int_{-1}^1 K(x,y)f(y)dy
$$
es solución del problema de frontera
$$
u''+u'+u=f(x), \qquad u(-1)=u(1)=0.
$$
:::

<details>
<sumary>**Solución**</summary>

</details>

---

:::{.exercise}
Calcula el núcleo $K$ tal que
$$
u(x) := \int_{0}^1 K(x,y)f(y)dy
$$
es solución del problema de frontera
$$
u''=f(x), \qquad u(0)=u'(1)=0.
$$
:::

<details>
<sumary>**Solución**</summary>

</details>

---

:::{.exercise}
Sea $f$ una función $L$-periódica. Calcula una fórmula de representación integral para las soluciones $L$-periódicas de la ecuación $u''=f$. ¿Tiene este problema soluciones para toda $f$ o hace falta alguna condición? De existir las soluciones, ¿son únicas?
:::

<details>
<sumary>**Solución**</summary>

</details>

---

:::{.exercise}
Calcula la f'ormula de representacion para la solución de la ecuación de Poisson en la bola $B_r \subset \mathbb R^n$ con lado derecho radial, es decir $f=f(\rho)$ con $\rho=|x|$
$$
\begin{cases}
\Delta u = f \text{ en } B_r,\\
u=0\text{ in } \partial B_r.
\end{cases}
$$
:::

<details>
<summary>**Solución**</summary>
Una solución radial $u=u(\rho)$ satisface
$$
\rho^{1-n}(\rho^{n-1}u')'=f, \qquad u'(0)=u(r)=0.
$$
Por lo que integrando un par de veces recuperamos
$$
u(\rho) - u(0) = \int_0^\rho \int_0^s \frac{t^{n-1}}{s^{n-1}}f(t)dtds = \frac{1}{2-n}\int_0^\rho \left(\frac{t^{n-2}}{\rho^{n-2}}-1\right)tf(t)dt.
$$
Para hacer $u(r)=0$ tomamos
$$
u(0) = -\frac{1}{2-n}\int_0^r \left(\frac{t^{n-2}}{r^{n-2}}-1\right)tf(t)dt.
$$
Por lo tanto
$$
u(\rho) = \int_0^r K(\rho,t)f(t)dt, \qquad K(\rho,t) = \frac{t}{2-n}\left(\left(\frac{t^{n-2}}{\rho^{n-2}}-1\right)1_{t\leq \rho}-\left(\frac{t^{n-2}}{r^{n-2}}-1\right)\right).
$$
</details>

---

:::{.exercise}
Calcula la f'ormula de representacion para la solución de la ecuación de Poisson en la bola $B_r \subset \mathbb R^n$ con lado derecho radial, es decir $f=f(\rho)$ con $\rho=|x|$
$$
\begin{cases}
\Delta u - \omega^2 u = f \text{ en } B_r,\\
u=0\text{ in } \partial B_r.
\end{cases}
$$
:::

<details>
<summary>**Solución**</summary>
</details>